### ISSUE TITLE
BSOD после использования на x32 

### ISSUE THREAD

**Issue by Segr** [farag2/Windows-10-Setup-Script#12]
https://yadi.sk/i/XuzM61HKkqc4Ug

**Comment by farag2** [comment]
Скрипт никогда не тестировался на x86-системах. В описании это указано.
Да и какая-нибудь Песочница виновата.

**Comment by Segr** [comment]
нет, только что проверил
чистая винда, только поставленная, при рестарте после применения скрипта - падает

**Comment by Segr** [comment]
Hyper-V 2012R2 
Чистая установка Windows Pro x32 RUS
Рушится при перезагрузке после любого выполнения из скрипта "Disable-WindowsOptionalFeature..."

**Comment by farag2** [comment]
@Segr, ну это что-то с виндой. Получается, не может, отключить компоненты. :)

**Comment by farag2** [comment]
@Segr, https://github.com/farag2/Windows-10-Setup-Script/issues/14#issuecomment-531564558
