### ISSUE TITLE
Ошибки после запуска скрипта.

### ISSUE THREAD

**Issue by likegos** [farag2/Windows-10-Setup-Script#13]
Hi, during script running, I faced this errors.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:1645 знак:31
+         $apps = Read-Host -Prompt " "
+                                     ~
Непредвиденная лексема ""
		IF ($apps -match "" в выражении или операторе.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:1646 знак:25
+         IF ($apps -match ".exe" -and $apps -match "`"")
+                               ~~~~~~~~~~~~~~~~~~~~~
Непредвиденная лексема "" -and $apps -match "" в выражении или операторе.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:1646 знак:46
+         IF ($apps -match ".exe" -and $apps -match "`"")
+                                                    ~~~~
Непредвиденная лексема "`"")
		{
			GpuPreference $apps
		}
		elseif ([string]::IsNullOrEmpty($apps))
		{
			break
		}
		else
		{
			IF ($RU)
			{
				Write-Host "`nРџСѓС‚Рё РЅРµ РІР·СЏС‚С‹" в выражении или операторе.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:1687 знак:2
+     {
+     ~
Отсутствует закрывающий знак "}" в блоке операторов или определении типа.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:1685 знак:1
+ {
+ ~
Отсутствует закрывающий знак "}" в блоке операторов или определении типа.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:1491 знак:1
+ {
+ ~
Отсутствует закрывающий знак "}" в блоке операторов или определении типа.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:1694 знак:56
+ ...          IF ((Get-CimInstance вЂ“ClassName CIM_ComputerSystem).Hyperv ...
+                                                                  ~
Отсутствует ключевое слово while или until в цикле do.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:747 знак:1
+ {
+ ~
Отсутствует закрывающий знак "}" в блоке операторов или определении типа.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:1694 знак:56
+ ...         IF ((Get-CimInstance вЂ“ClassName CIM_ComputerSystem).Hypervi ...
+                                                                 ~
Непредвиденная лексема ")" в выражении или операторе.
C:\Users\vissay\Desktop\Windows-10-Setup-Script-4.0.4\Win10.ps1:1694 знак:85
+ ... nstance вЂ“ClassName CIM_ComputerSystem).HypervisorPresent -eq $true)
+                                                                         ~
Непредвиденная лексема ")" в выражении или операторе.
Выданы сообщения не обо всех ошибках синтаксического анализа.  Исправьте перечисленные в сообщениях ошибки и повторите попытку.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by farag2** [comment]
Каким методом запускается скрипт?
