### ISSUE TITLE
Автоматическое создание точки восстановления в начале работы

### ISSUE THREAD

**Issue by the-vindicar** [farag2/Windows-10-Setup-Script#14]
Имеет смысл, вдруг что-то пойдёт не так.

**Comment by farag2** [comment]
Не запрещаю добавить для себя, но не люблю, когда да ручку водят пользователя. Пользователь сам должен отдавать отчёт, что он делает.
@the-vindicar, И, да, на x86-системах никогда не тестировался скрипт и не будет тестироваться. В описании указана необходимая разрядность ОС. И пора уже увеличить объем оперативной памяти: на 3 ГБ никто не сидит. :)

**Comment by the-vindicar** [comment]
Хуже, 2ГБ. Вот позарез надо поставить именно десятку и именно на такую машинку (старый ноут). Надеялся найти пачку оптимизаций в одном скрипте.

А вот насчёт точки восстановления не понял. Сами же на хабре писали, что не отключаете защитные меры по умолчанию - так почему не воспользоваться одной из самых надежных перед выполнением рискованной операции?

**Comment by farag2** [comment]
@the-vindicar, ибо такое пользователи могут сами сделать. Возможно, поставлю на виртуалку 32-разрядную версию и посмотрю, от чего ей так плохо.

**Comment by farag2** [comment]
@the-vindicar, набрался сил и поставил X86 Win 10. Опытным путем выяснил, что BSoD и правда вылезает от... отключения компонентов (# Turn off Windows features # Отключить компоненты). Да, почему-то после отключения компонента "FaxServicesClientPackage" просто падает ОС. Но почему именно на x86?

```
FeatureName      : FaxServicesClientPackage
DisplayName      : Факсы и сканирование Windows
Description      : Разрешить выполнение задач обработки факсов и сканирования на данном компьютере
RestartRequired  : Possible
State            : Enabled
CustomProperties : 
```

Что хочешь, то и делай...

**Comment by farag2** [comment]
@the-vindicar, список того, чтобы надо исправить, чтобы на x86 не было ошибок:

Перед

```
New-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy -Name 01 -PropertyType DWord -Value 1 -Force
```

надо принудительно создать ключ (на x86 его нет в отличии от x64)

```
IF (-not (Test-Path -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive))
{
	New-Item -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive -Force
}
New-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy -Name 01 -PropertyType DWord -Value 1 -Force
```

Удалить строку

```
New-ItemProperty -Path "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Thumbnail Cache" -Name Autorun -PropertyType DWord -Value 0 -Force
```

Изменить путь установщика OneDrive на

```
Start-Process -FilePath "$env:SystemRoot\System32\OneDriveSetup.exe" -ArgumentList "/uninstall" -Wait
```

Удалить строку

```
New-ItemProperty -Path HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework -Name OnlyUseLatestCLR -PropertyType DWord -Value 1 -Force
```

Вместо

```
Remove-Printer -Name Fax, "Microsoft XPS Document Writer", "Microsoft Print to PDF" -ErrorAction SilentlyContinue
```

надо

```
Remove-Printer -Name Fax -ErrorAction SilentlyContinue
```

В x86 просто нет по умолчанию "Microsoft XPS Document Writer" и "Microsoft Print to PDF"

Удалить раздел "# Включить Windows Sandbox", так как очевидно Windows Sandbox не работает на x86.

И про удаление "FaxServicesClientPackage" не забываем!

**Comment by the-vindicar** [comment]
Спасибо!

**Comment by Segr** [comment]
Зачем удалять строки? можно же "if ([System.Environment]::Is64BitOperatingSystem) {"

И непонятно принудительное создание ключа "HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive" именно перед этой строчкой, тем более что это делается ниже.

**Comment by farag2** [comment]
@Segr, @the-vindicar волен делать, как хочет; я лишь предложил самый простой путь.
 Я опечатался! Спасибо.

**Comment by Segr** [comment]
а предложенный путь для одного, который волен делать как хочет, можно оформить в виде патча?

**Comment by farag2** [comment]
Можно. :) То есть выложить код, чтобы была проверка на битность? Если x64, то продолжить, если x86, то break?
