### ISSUE TITLE
Профили

### ISSUE THREAD

**Issue by scriptingstudio** [farag2/Windows-10-Setup-Script#16]
Неплохо было бы разделить настройки компьютера и пользователя, чтобы настраивать отдельно.

**Comment by farag2** [comment]
Не представляю, как бы все это выглядело. Да и тем более все равно делается с божьей помощью версия с GUI. В конечном счете будут поддерживаться 2 версии сразу.

**Comment by scriptingstudio** [comment]
а где версия с гуем?

**Comment by farag2** [comment]
Макет и постоянно обновляющиеся файлы в ветке "GUI-dev". Делает ее @oz-zo.
