### ISSUE TITLE
Taskmgr

### ISSUE THREAD

**Issue by emris97** [farag2/Windows-10-Setup-Script#19]
Когда скрипт доходит до следующего кода, который запускает диспетчер задач, падает ошибка
![photo_2019-12-24_14-51-14](https://user-images.githubusercontent.com/32432604/71409985-e93a9a00-265c-11ea-9378-4b74b9f864bb.jpg)

Но как только я открываю диспетчер задач с помощью ctrl+shift+esc, скрипт продолжает работу.

**Comment by farag2** [comment]
@emris97, я давно уже на больничном. Но я так понимаю, что надо написать просто taskmgr.exe (без .\).

**Comment by farag2** [comment]
@emris97, кодировка файла какая?
