### ISSUE TITLE
Error after run (win10 x64 insider)

### ISSUE THREAD

**Issue by necros2k7** [farag2/Windows-10-Setup-Script#20]
PS Z:\> .\win10.ps1
Z:\win10.ps1:726 знак:2
+     {
+     ~
Отсутствует закрывающий знак "}" в блоке операторов или определении типа.
Z:\win10.ps1:724 знак:1
+ {
+ ~
Отсутствует закрывающий знак "}" в блоке операторов или определении типа.
Z:\win10.ps1:733 знак:56
+ ...         IF ((Get-CimInstance вЂ“ClassName CIM_ComputerSystem).Hypervi ...
+                                                                 ~
Непредвиденная лексема ")" в выражении или операторе.
Z:\win10.ps1:733 знак:85
+ ... nstance вЂ“ClassName CIM_ComputerSystem).HypervisorPresent -eq $true)
+                                                                         ~
Непредвиденная лексема ")" в выражении или операторе.
Z:\win10.ps1:890 знак:2
+     }
+     ~
Непредвиденная лексема "}" в выражении или операторе.
Z:\win10.ps1:891 знак:1
+ }
+ ~
Непредвиденная лексема "}" в выражении или операторе.
Z:\win10.ps1:949 знак:2
+     }
+     ~
Непредвиденная лексема "}" в выражении или операторе.
Z:\win10.ps1:950 знак:1
+ }
+ ~
Непредвиденная лексема "}" в выражении или операторе.
Z:\win10.ps1:1347 знак:77
+ ...  = "Р¤Р°Р№Р»С‹ СЂРµРµСЃС‚СЂР° (*.reg)|*.reg|Р’СЃРµ С„Р°Р№Р»С‹ (*.*)|* ...
+                                                          ~~~~~~~~
Непредвиденная лексема "Р°Р№Р»С‹" в выражении или операторе.
Z:\win10.ps1:1816 знак:193
+ ... /c DISM /Online /Add-Package /PackagePath:`"%1`" /NoRestart & pause"  ...
+                                                                 ~
Амперсанд (&) не разрешен. Оператор & зарезервирован для будущих версий. Добавьте двойные кавычки до и после амперсанда ("&"), чтобы передать его как строку.
Выданы сообщения не обо всех ошибках синтаксического анализа.  Исправьте перечисленные в сообщениях ошибки и повторите попытку.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

**Comment by farag2** [comment]
https://github.com/farag2/Windows-10-Setup-Script/blob/master/README.md#usage
Не читаем инструкцию. :)
