### ISSUE TITLE
Вопрос по замене $OFS

### ISSUE THREAD

**Issue by carloscondit** [farag2/Windows-10-Setup-Script#21]
Добрый день!
Я новичок в powershell и пытаюсь использовать ваш скрипт в своих целях. У меня вопрос есть вопрос по одному из действий в скрипте. Несколько раз перед выполнением некоторых операций разделитель массива строки $OFS меняется с пробела на символ "|", а после выполнения операции меняется обратно на пробел. В частности в той части скрипта на удаление UWP-приложений. Подскажите, пожалуйста, с какой целью это делается? Ведь без этой замены UWP-приложения также удаляются.

**Comment by farag2** [comment]
Доброй ночи. Ну, разделитель такой нужен. Разве работает без него? Вообще советуют мне использовать
  ```powershell
-join '|'
```
то есть
  ```powershell
Get-AppxPackage -PackageTypeFilter Bundle -AllUsers | Where-Object -FilterScript {$_.Name -cmatch ($AppxPackages -join '|')} | Remove-AppxPackage -AllUsers -Verbose
  ```

**Comment by carloscondit** [comment]
Большое спасибо за разъяснение! Я совсем не туда смотрел и поспешил задать вопрос. Для меня результатом того, что все работает без "|", было тот факт что приложения удалились. НО! Они удалились все, вместо того, чтобы остались приложения из списка исключений. Я не сразу понял что этот разделитесь работает на фильтр, в котором имя приложения из списка сравнивается по **конвейеру** со списком исключений.  А без него каждое приложение из списка сравнивается со строкой, в которой имена приложений-исключений указаны через пробел. Я ведь правильно все понял?!
И не сочтите за наглость, хочу спросить совета по литературе или другому источнику знаний по PowerShell. В данный момент я прочитал "Введение в Windows PowerShell" Андрея Попова. Хотелось бы еще что-нибудь в таком роде, но более подробное и про современный PowerShell. Нашел еще Bruce Payette - Windows Powershell in Action, но оно на английском и боюсь что на его изучение у меня очень много времени уйдет,. Заранее благодарен!

**Comment by farag2** [comment]
@carloscondit, есть аккаунт на каком-либо сайт, перечисленном в скрипте, чтобы туда в ЛС скинул? Или только сюда? 
Да, про палочку правильно понял.

**Comment by carloscondit** [comment]
@farag2 у меня есть учетки на сайтах: [Хабр,](https://habr.com) [4PDA](https://4pda.ru) и [RU-BOARD.](http://forum.ru-board.com/) На всех ник bazki. Ответьте на тот сайт, где Вам удобнее.

**Comment by farag2** [comment]
@carloscondit, отправил ссылки через ru-board.

**Comment by carloscondit** [comment]
@farag2 Большое спасибо!
