### ISSUE TITLE
Скрипт не запускается

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [farag2/Windows-10-Setup-Script#22]
В связи с тем, что скрипт не подписан сертификатом, он просто не отработает. Более того - из батника пришлось убирать -remotesigned.
Если предполагается отключение политик или выполнять другие действия для работы, то следует написать об этом в Readme.

**Comment by farag2** [comment]
Как это он не запускается-то? И зачем было убирать -RemoteSigned? И какие еще политики отключаются? Скрины нужны.

**Comment by danijeljw** [comment]
It would be better to use `-ExecutionPolicy -ByPass` instead. Also set the scope to the current process like this `-Scope Process` like this:

### Start.cmd
```cmd
@echo off
chcp 65001 >nul

powershell.exe -ExecutionPolicy ByPass -Scope Process -NoExit -NoProfile -NoLogo -File "%~dp0Win 10.ps1"
```
<hr />

Ref: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7

**Comment by gandalfthewhite19890404** [comment]
I gonna try script with PR changes and report here, sure.

**Comment by farag2** [comment]
@gandalfthewhite19890404, fixed Start.cmd. Wrong enconding. Rereleased 4.3.0.1 with fixed one.

**Comment by gandalfthewhite19890404** [comment]
Script works now, I closing this issue.
