### ISSUE TITLE
Error during script's work + feature request

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [farag2/Windows-10-Setup-Script#25]
Here is screenshots with several errors, maybe some of them are OK (especially warning about network connection - virtual machine does not have it, I just installed Windows 10 Pro 1909).
And what i should choose at screenshot №4?
[Windows 10.zip](https://github.com/farag2/Windows-10-Setup-Script/files/4672088/Windows.10.zip)

Feature request - make changing Desktop, Documents and other userfolders optional and skippable - I usually doint it by myself, and solution in script not understandable for me at all - Why script moving them to root of harddrive (not folder choosed by user), why user should move his files by own, what happens with current files - I don't see Users folder in C Drive?

**Comment by farag2** [comment]
Советую использовать Hyper-V вместо VirtualBox, если редакция Windows выше Home.
Что выдаст виртуалка, если
```powershell
Set-StrictMode -Version latest
$RAMCapacity = (Get-CimInstance -ClassName Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum).Sum/1kb
New-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control -Name SvcHostSplitThresholdInKB -PropertyType DWord -Value $RAMCapacity -Force
```
```
not folder choosed by user
```
Для этого и написана функция вообще-то:
https://github.com/farag2/Windows-10-Setup-Script/blob/master/Win%2010.ps1#L1478
То есть вместо папки FolderPath в вызове функции
``` powershell
UserShellFolder -UserFolder Desktop -FolderPath "${SelectedDrive}:\Desktop"
```
пишем
```powershell
UserShellFolder -UserFolder Desktop -FolderPath "${SelectedDrive}:\myfolder\folderforaporn\Desktop"
```
и так далее. Папки сами создадутся. Просто самое правильное решение - Держать в корне какого-либо диска, а не в задница мира, вроде
```
C:\Users\username\Desktop
```
```
why user should move his files by own, what happens with current files
```
Представь ситуацию (кою я наблюдаю частенько): люди держат даже фильмы на рабочем столе и под 300 файлов в папках, так как еще не дошел до них прогресс в виде внешних жестких дисков, держание ярлыков в Пуске и на начальном экране. И вся эта каша, которую никто не разгребает, будет перемещаться со скоростью черепахи на другой диск, например. Человека или подумает, что все зависло (а те, кто не подумают, допишут функцию, чтобы перемещало все файлы. Поэтому и выдается предупреждение о том, что 
```powershell
if ($RU)
{
	$Title = "Выберите букву диска, в корне которого будет создана папка для `"Рабочий стол`".`nФайлы не будут перенесены: сделайте это вручную"
}
else
{
	$Title = "Choose the drive letter in the root of which the `"Desktop`" folder will be created.`nFiles will not be moved. Do it manually"
}
```
Чтобы пропустить вовсе переопределение пользовательских папок, можно или вообще удалить весь раздел, или, что быстрее, закомментировать каждое выполнение функций отрисовки меню и, собственно, отработки перемещения:
```powershell
$SelectedDrive = ShowMenu -Title $Title -Menu $DriveLetters -Default $Default
UserShellFolder -UserFolder Desktop -FolderPath "${SelectedDrive}:\Desktop"
```
И так для каждой папки. Может, позже подумаю над непосредственно переносом файлов, но боюсь, что это может выйти боком: что-то открыто у людей, куда-то нет доступа. Легче так. Это же автоматизация. Кто не понимает сие, могу через саму винду сделать. Там всего одна кнопка.
Вообще на самом деле лучше удалить Start.cmd. Лучше научить людей запускать непосредственно сам ps1 файл.

**Comment by farag2** [comment]
В принципе можно переписать с возможностью ручного выбора папки, уйдя от выбора дисков. Не взлетело, видать...

**Comment by gandalfthewhite19890404** [comment]
пусть оно будет опционально, и в случае выбора положительного ответа - предложить выбрать папку. Я обычно сразу делаю такое, но путем вырезания папки из папки пользователя. И поскольку это делается на чистой системе - то и процесс быстрый. И скрипт предназначен для выполнения на свежей системе - поэтому папки будут относительно пустые.
Может сделать проверку даты установки системы и в случае превышения количества дней - например один или два дня - то вывести предупреждение, с выбором продолжения.

**Comment by farag2** [comment]
Подумаю в общем. Выяснилось, что PS не умеет по-нормальному создавать окошко выбора папки а-ля Vista, только как в XP. Надо будет думать. А так уже код набросал.

**Comment by s3rj1k** [comment]
+ За опциональность переноса пользовательских папок.
P.S. За скрипт спасибо :)

**Comment by farag2** [comment]
;)

**Comment by farag2** [comment]
@gandalfthewhite19890404, обновил. Смотри. :)
