### ISSUE TITLE
Strange things...

### ISSUE THREAD

**Issue by TheAresjej** [farag2/Windows-10-Setup-Script#27]
### I used your script and strange things are happening here.

1.  **Windows Wallet on startup** - why? x1
![image](https://user-images.githubusercontent.com/19390797/85209970-9c4e2c80-b33c-11ea-9d7e-344a77d7bd10.png)

2.  **Seconds on timer** - why? x2
![image](https://user-images.githubusercontent.com/19390797/85209648-e681de80-b339-11ea-862e-997a3cf35113.png)

3.  **Windows sandbox install** - why? x3
![image](https://user-images.githubusercontent.com/19390797/85209658-f4cffa80-b339-11ea-88e1-7ef22fb4ee0f.png)

4.  **ribbon view on default** - why? x4
![image](https://user-images.githubusercontent.com/19390797/85209683-2e086a80-b33a-11ea-937d-8b1113abce71.png)

5.  **Powershell folder in documents** - okey let's skip

![image](https://user-images.githubusercontent.com/19390797/85209700-51331a00-b33a-11ea-9e13-b41265d09b85.png)

it's only a few minutes after the reboot, so there could be more. 🙉

### **Script version:**
![image](https://user-images.githubusercontent.com/19390797/85209806-08c82c00-b33b-11ea-9155-94afba5af307.png)

### **OS informations:**
![image](https://user-images.githubusercontent.com/19390797/85209737-9b1c0000-b33a-11ea-83cc-602e1591c683.png)

**Comment by farag2** [comment]
I do not even know what are you writing about. You have execute the 3300 lines script without releiziling what it does on every line of script.
Before executing you NEED to know what you are executing and comment out every line you do not what to be sexecuted.
