### ISSUE TITLE
Revert tray icon changes

### ISSUE THREAD

**Issue by aminya** [farag2/Windows-10-Setup-Script#28]
How can I rever the tray icon to its previous state? Now all of the icons are shown, which I do not like
![image](https://user-images.githubusercontent.com/16418197/85235556-7cba1100-b3db-11ea-810f-e00d10b7b76d.png)

I managed to bring my search bar in the toolbar back, but I could not fix tray icon. 

In my opinion, this script should give an option for skipping all the UI changes!

**Comment by Yird1** [comment]
Here is a small fix:

1: Open regedit
2: Go To Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer
3: On the right, find (In quotes) "EnableAutoTray"
3b: If that doesn't exist, right click in blank space and go to new>DWORD (32-bit) value.
Then name it "EnableAutoTray" without the quotes.
4: Double click on it and change the number from 0 to 1
5: Click ok and then restart your PC

**Comment by farag2** [comment]
Before executing the whole script you MUST read every line. That's important!

**Comment by aminya** [comment]
There is nothing in the readme saying that this script will hide the search bar, will make the tray icon like win XP, etc. 

In the script, it was just asking for the theme color. I didn't know color means more than that.

**Comment by farag2** [comment]
@aminya, of course it isn't written because there are more than 150 functions in the script. I described only core features. Anf due to this CLI I won't add requests for every action. That's why it's called CLI!

**Comment by aminya** [comment]
It does not need to be CLI options. It could be a menu.

#31
