### ISSUE TITLE
Revert Time Format From Long To Short

### ISSUE THREAD

**Issue by hackingguy** [farag2/Windows-10-Setup-Script#29]
![bug](https://user-images.githubusercontent.com/28388650/85280106-1e596500-b4a5-11ea-9126-c1ea2b06a543.png)
Time Showing In Seconds!! Can U help Me Revert it!!!

**Comment by farag2** [comment]
First of all: you MUSTN'T execute the whole script before reading every line of it. I wrote it in the readme file.
Anyway open regedit and navigae to

```
HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
```
where delete the "ShowSecondsInSystemClock" key. Then log off or reboot.

**Comment by hackingguy** [comment]
Thanks a lot sir!
