### ISSUE TITLE
Stuck at Microsoft.549981C3F5F10_8wekyb3d8bbwe\CortanaStartupId' because it does not exist.

### ISSUE THREAD

**Issue by rsrini7** [farag2/Windows-10-Setup-Script#30]
Before submitting a bug report:

- Make sure you are able to repro it on the latest released version;
- The .ps1 file has UTF-8 with BOM enconding.

**Steps to reproduce**
------------------
Download latest from release for 2004 version and execute with admin prev.

**Screenshots**
<img width="563" alt="Capture0" src="https://user-images.githubusercontent.com/5178105/85288970-4e5c3480-b4b4-11ea-829c-9155496d9440.PNG">
<img width="557" alt="Capture" src="https://user-images.githubusercontent.com/5178105/85288981-51efbb80-b4b4-11ea-83e7-893ea2fabe4c.PNG">

**Desktop (please complete the following information):**
Version 2004 (OS build  19041.329)

**Additional context**

**Not sure about below changes: **
* print hot key replaced with inbuilt tool and my greenshot not working. after restart - realized the new feature is awesome.
* task bar right side icons auto expanded and there is no hidden items (its ok, but it reduces the space from middle)

**Comment by rsrini7** [comment]
It took very long time after the second screenshots and exited.

Line Errors/Warnings
---- ---------------
 886 This configuration is managed by an Administrator. Access is denied.
2430 Cannot find path 'HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Sy
     stemAppData\Microsoft.549981C3F5F10_8wekyb3d8bbwe\CortanaStartupId' because it does not exist.

**Comment by farag2** [comment]
@rsrini7
> This configuration is managed by an Administrator. Access is denied.
Because some configuration is managed by an Administrator. Likely you setup this feature before using GPO. So to setup it again you need to disable this policy.

> because it does not exist.
My fault.
Execute

```
# Turn off Cortana autostarting
if (Get-AppxPackage -AllUsers -Name Microsoft.549981C3F5F10)
{
	if (-not (Test-Path -Path "Registry::HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\Microsoft.549981C3F5F10_8wekyb3d8bbwe\CortanaStartupId"))
	{
		New-Item -Path "Registry::HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\Microsoft.549981C3F5F10_8wekyb3d8bbwe\CortanaStartupId" -Force
	}
	New-ItemProperty -Path "Registry::HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\Microsoft.549981C3F5F10_8wekyb3d8bbwe\CortanaStartupId" -Name State -PropertyType DWord -Value 1 -Force
}
```
