### ISSUE TITLE
Pc freezes after a bit while watching streaming\playing game

### ISSUE THREAD

**Issue by omgfrost** [farag2/Windows-10-Setup-Script#33]
Before submitting a bug report:

- Make sure you are able to repro it on the latest released version;
- The .ps1 file has UTF-8 with BOM enconding.

**Steps to reproduce**
After i run latest Win.10.2004.4.5.3.zip on my latest windows 10 2004 version. Everytime i watch streaming or gaming online my pc freezes and nothing can be done. Even the keyboard is stuck, the whole system is stuck and the only way is the reset button.
I'm pretty sure it's the script because when i go to previous created restore point,computer smooth like ever before running the script.
Also another important thing: Browsing the pages and overall internet is very slow\sluggish as it's not after restore point is done.
How can i solve without using restore point since i want all the bloatwares and telemetry away?
Thanks in advance

```PowerShell

```
![bvVGlNa 1](https://user-images.githubusercontent.com/14861120/85883892-086bdd00-b7e2-11ea-9ba0-a29948a7a576.png)

**Screenshots**
https://i.imgur.com/bvVGlNa.png

**Desktop (please complete the following information):**
- Windows build: See screenshot link above

**Additional context**

**Comment by omgfrost** [comment]
I don't know if is this causing the issue because it's being online and no freezes since 1 hour at least after restore point.
Anyway i use this:
```
`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\brave.exe]
"UseLargePages"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Hearthstone.exe]
"UseLargePages"=dword:00000001`
```

**Comment by farag2** [comment]
@omgfrost, hello. The script is not causing any issues due to I'm using only official registry keys and cmdlets. So as I mentioned in FAQ section

```
Running the script is best done on a fresh install because running it on tweaked system may result in errors occurring.
```

The script has been tested on hundreds of PC systems and not a single problem was observed. I think you tweaked a lit bit your OS that is causing this issue.

>  Now that i was peeking in event log i got every 2 mins DCOM Errors and the ID should be Cortana

What have your done with it? :) Cortana can be uninstalled or disabled from autostarting. It can not be causing any issues.

Summarize
Running the script cannot increase ping or latency. I advice to run it after fresh install.

**Comment by omgfrost** [comment]
trust me, i really really want to have it run in my box but its just that freezing my pc.Im now on restore point and didnt freeze a single time without it and im running streams and games at same time.
So please i need help to catch what can conflict with it. my boxvis not overcloackedvat all as im on i3 on a 2014 gygabye mobo.
All i have done here is running wpd.app and windows10 debloater script gui which is very similar to yours but it didnt cause me any issues.
If you want to take a look at those mentioned programs go ahead and maybe you will find what conflicts with your script.
Please, i will help you helping me if you need some specific information of my running system i will provide them.
About the DCOM error, it started after i run the script and now it stopped since 2 hours.ive run this for disabling cortana: https://www.msn.com/en-gb/money/technology/windows-10-may-2020-update-finally-makes-it-easy-to-ditch-cortana/ar-BB14V1g
as with your script, it hung at removing microsoft.549981C3F5F10- which is cortana so after waiting half an hour i pressed ctrl+c to interrupt the script.
Is the script finished after that package or it keeps running?

**Comment by farag2** [comment]
Do you have an account on reddit or on others sites mentioned in readme? May be I'll be able to help via TeamViewer. Cuz I have no idea without seeing the OS

**Comment by omgfrost** [comment]
in the other issue reported by me here theres the link to my reddit in which you replied me to open an issue here in github so yeah its the one with ms store connection after running the script which i did 2 times with same restore point and both times store had connection problem on which i ve solved by re registering it with that ps cmdlet plus wsreset.
So yeah thats my account on reddit. tell me what to do.
ps. i dont have microphone so we have to type in notepad or smth if you proponing a tv session

**Comment by farag2** [comment]
Check the PM on reddit.
