### ISSUE TITLE
Darkmode turns taksbar blue

### ISSUE THREAD

**Issue by zodina34** [farag2/Windows-10-Setup-Script#36]
Latest 2004 version turns taksbar blue in dark mode.

**Comment by farag2** [comment]
Know about it. No idea how to fix it. Back to it on Monday.

**Comment by omgfrost** [comment]
a workaround is to go settings, appearance, color scroll all the way down and uncheck last both option if you are already in dark mode, titles and taskbar will go back to "black" color
