### ISSUE TITLE
Script Error while creating ProcessCreation.xml

### ISSUE THREAD

**Issue by sidthepro** [farag2/Windows-10-Setup-Script#37]
The Script is showing an error (Line 3165 Could not find a part of the path 'C:\ProgramData\Event Viewer\Views\ProcessCreation.xml) on Fresh Windows 10 Pro 2004 install i think the script is trying to create a file in a folder which doesn't exist.

**Comment by farag2** [comment]
Just have found out by myself. Will release a new version in an hour.

**Comment by sidthepro** [comment]
Btw what does this ProcessCreation.xml do? is it important?

**Comment by farag2** [comment]
Actually nothing is important in our life. I just automated stuff from this article: https://devblogs.microsoft.com/commandline/how-to-determine-what-just-ran-on-windows-console/
I think it's important if you want to know which processes start with its commandline arguments.
