### ISSUE TITLE
Can only add one App to High Graphics Performance

### ISSUE THREAD

**Issue by shuntera** [farag2/Windows-10-Setup-Script#39]
After adding the first one and getting back to the script, pressing 'A' again does nothing, it just takes you to the next part of the script.

**Comment by unsaved** [comment]
I tried running this script on 4 different PCs.  On 3 it behaved exactly as shunera explained.  On 4th I don't get the prompt even once.  The prompt text may be in the hundreds of debug info that flies by, but there's no opportunity for me to enter any input.

**Comment by farag2** [comment]
Thanks. Confirmed. Will release a new version tomorrow.
