### ISSUE TITLE
Bad user input behavior

### ISSUE THREAD

**Issue by unsaved** [farag2/Windows-10-Setup-Script#41]
User entered text often doesn't produce the results stated in the prompt.  This is at least as bad with current version as from the version 1 week ago.

At 2 or 3 points during script execution the program just stops progressing and no prompt is given.  Hitting the space bar nudges the script to continue.

At several points during script execution the prompt will not accept ENTER key until I enter some other key first.  Sometimes hitting ENTER multiple times works, but I fear doing that because I don't know if it buffers up the multiple ENTERs to use the for subsequent prompts. 

Sometimes prompts won't take any input at all until I refocus on the window (though I did nothing to take focus away from the script execution window).

Sometimes when I re-run it to see if disabled apps have reverted (which happened many times), if I see all of the apps are removed and nothing to do so just close the app-sel UI, the script freezes and there's nothing I can do but close the script window.

**Comment by farag2** [comment]
I can not reproduce. Tested on hundreds PCs. Never faced that.
https://github.com/farag2/Windows-10-Setup-Script#faq
