### ISSUE TITLE
Script only runs on 64bit system

### ISSUE THREAD

**Issue by houneie** [farag2/Windows-10-Setup-Script#42]
![image](https://user-images.githubusercontent.com/23403229/86752607-e895ae00-c058-11ea-9f98-84431d4c8e05.png)

I recently installed 32-bit version Windows 10 2004 when I ran your script it gave me an error that the system isn't supported.

**Comment by farag2** [comment]
Of course it runs on x64 systems only. What is the question?

**Comment by houneie** [comment]
Is there any way that I can run this on 32-bit system?

**Comment by farag2** [comment]
No. the x86 systems are obsolete. I haven't even PCs to test. If you can, update script to be able to run it on x86 OS.
