### ISSUE TITLE
SnippingTool (20H2)

### ISSUE THREAD

**Issue by EldarAron** [farag2/Windows-10-Setup-Script#45]
I ran the test version of of this tool (20H2). It worked great except for one thing. SnippingTool has now taken control of the PrintScreen key. I have used this key with Greenshot. I selected SnippingTool and note tools (not OneNote) to be uninstalled.
I ran the script again. But I still got the same apps for uninstallation. Second time I selected all users. Din't help. 

I have tried to disable SnippingTool with both reg. entry and policy entry. It still captures the Print Screen key. 

Any suggestions?

Keep up the good work! 👍🏻

**Comment by farag2** [comment]
https://github.com/farag2/Windows-10-Setup-Script/blob/fdb43aca596c5b90f5776e359106af0d6123c408/Win%2010%202004.ps1#L661

So to revert it run this

```
Remove-ItemProperty -Path "HKCU:\Control Panel\Keyboard" -Name PrintScreenKeyForSnippingEnabled -Force
```

**Comment by EldarAron** [comment]
Thanks!
I missed that one. Big thanks!
