### ISSUE TITLE
Send to gone after running the script

### ISSUE THREAD

**Issue by yusuf-madkour** [farag2/Windows-10-Setup-Script#46]
**Steps to reproduce**
------------------

Just run the latest version of the script (Win.10.1903-1909.4.4.6)

**Desktop:**
- Windows build: 18363

**Additional context**
The **send to option** from the context menu is gone. I have had the same exact result after running the script on two different devices after a fresh windows install.

I fixed that on both devices by editing a registry entry which had an extra hyphen in its value for some reason.

**Comment by yusuf-madkour** [comment]
I have just taken a look at your Win 10 1903-1909.ps1 file and realized that it is not an issue but a design decision made in line 3196, is it possible to ask the user about removing the option before actually removing it?

If there was a prompt asking about that already then I am sorry for wasting your time but I don't remember seeing one.

It could be a nice addition to your readme to avoid issues opened for this matter.

**Comment by farag2** [comment]
> is it possible to ask the user about removing the option before actually removing it?
It's possible of course. But while the project has CLI interface such ask won't be added due to there are about 150 functions. You prefer 150 asks? :)

> I don't remember seeing one.
You're right. Somewhere I added the ask somewhere didn't. But it's up to you to add such kind of thing whereever you want.

> It could be a nice addition to your readme to avoid issues opened for this matter.
I tried to. :)
https://github.com/farag2/Windows-10-Setup-Script#faq

Anyway here is a template you can use if want to add an ask before function run.

```powershell
$Title = " "
$Message = " "
$Options = "& ", "& ", "& " # & symbol is required. Add more options if ypu want.

$DefaultChoice = 1
$Result = $Host.UI.PromptForChoice($Title, $Message, $Options, $DefaultChoice)

switch ($Result)
{
	"0"
	{
		Do something
	}
	"1"
	{
		Do something # 2
	}
	"2"
	{
		Do something # 3
	}
}
```

**Comment by farag2** [comment]
Wait for 5.0 release. Going to add presets. Somewhere in 2020...
