### ISSUE TITLE
Changed Default Keyboard Layout in Login Screen

### ISSUE THREAD

**Issue by Siedhuss** [farag2/Windows-10-Setup-Script#47]
I installed Windows 2004 with german keyboard layout and german language settings.
After running the script with default settings, I had english default keyboard layout in the login screen.

I was able to change it back to german layout, but maybe thats a bug other users could also struggle with.
------------------
**Desktop (please complete the following information):**
- Windows build: 2004

**Comment by farag2** [comment]
Do not use script if you are not able to read [FAQ](https://github.com/farag2/Windows-10-Setup-Script#faq) and script itself
https://github.com/farag2/Windows-10-Setup-Script/blob/master/Win 10 2004.ps1#L1230
