### ISSUE TITLE
Mail and Calendar app not working

### ISSUE THREAD

**Issue by singhmanpo** [farag2/Windows-10-Setup-Script#50]
I might have missed some part of code, but, Mail and Calendar apps are crashing within seconds after opening.
Need help to revert this feature or function.

**Comment by farag2** [comment]
What sections did you ran?

**Comment by singhmanpo** [comment]
I ran something related to Microsoft communications. I think I went wrong there.

**Comment by farag2** [comment]
Hm. Can confirm...

**Comment by gtumanyan** [comment]
Mail, calendar and synchronization depend on

- OneSyncSvc - Синхронизация узла

- PimIndexMaintenanceSvc - Служба контактных данных

- UnistoreSvc - Служба хранения данных пользователя

- UserDataSvc - Служба доступа к данным пользователя

**Comment by farag2** [comment]
@gtumanyan, yeah, thought the same way. Need more tests.

**Comment by farag2** [comment]
So thanks for bug reporting and @gtumanyan. And from now I've forgot about blocking the Win 10 telemetry, The end.

```powershell
New-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\PimIndexMaintenanceSvc -Name Start -PropertyType DWord -Value 3 -Force
Remove-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\PimIndexMaintenanceSvc -Name UserServiceFlags -PropertyType DWord -Value 0 -Force
New-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\UnistoreSvc -Name Start -PropertyType DWord -Value 3 -Force
Remove-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\UnistoreSvc -Name UserServiceFlags -PropertyType DWord -Value 0 -Force
New-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\UserDataSvc -Name Start -PropertyType DWord -Value 3 -Force
Remove-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\UserDataSvc -Name UserServiceFlags -PropertyType DWord -Value 0 -Force
# Restart required
```

**Comment by orzymandias** [comment]
Hi, I already tried reinstalling as per #52 but issue still persists. I realised UserDataSvc  is no longer in my services.msc what can I do to resolve this? Much appreciated.
