### ISSUE TITLE
Ps4 remote play breaks even after restoring to a previous point

### ISSUE THREAD

**Issue by Volcano1002** [farag2/Windows-10-Setup-Script#51]
I ran into this issue first when I used the debloater for 1909, but I didn't create a restore point.
Reïnstalling ps4 remote play also didn't work,  I couldn't even reïnstall it at first  because I had to re-enable media pack features and install and setup windows media player. But after doing that and reïnstalling ps4 remote play I get the error "cannot connect to server".

I updated to windows 2004 and It started working again. Ran the debloater and made sure media pack wasn't disabled and made a restore point. After the debloater ran the same problem occurs "can't connect to server".
So I decided to return to the restore point so I could pin down what service or process was the problem, but I still get the error after restoring.

Right now I can't get the ps4 remote play programm to open. It gets stuck on the error.
![ps4RmtPlatPNG](https://user-images.githubusercontent.com/32981421/89725961-bd1a3080-da15-11ea-8766-7754cdbf0225.PNG)

**Comment by farag2** [comment]
Unfortunately do not have PS4. I do not know how to test. Asked a question on a forum. May be members will help.

**Comment by Volcano1002** [comment]
> 
> 
> Unfortunately do not have PS4. I do not know how to test. Asked a question on a forum. May be members will help.

No the app can't even open. It fails to launch. Normally you get to a log in or sync screen, but the app just gives the can't connect window. You don't need a ps4 for just launching the program.

**Comment by farag2** [comment]
OK. Investigating...

**Comment by Volcano1002** [comment]
> 
> 
> OK. Investigating...

Thank you for your time investigating this issue.

**Comment by farag2** [comment]
Confirmed. Need more time.

**Comment by farag2** [comment]
And here is the fix

```powershell
New-Item -Path $env:LOCALAPPDATA\Temp -ItemType Directory -Force
```

Just create this folder, and voila the app is able to connect! As I tested on my own and virtual PCs, no need to restart.

**Comment by Volcano1002** [comment]
Thank you very much.
