### ISSUE TITLE
Windows build 1909 Microsoft Mail doesn't login with my computer account

### ISSUE THREAD

**Issue by binarydepth** [farag2/Windows-10-Setup-Script#52]
Open Mail and try to login, it will say account already exists and doesn't let me click on "Go to inbox"
------------------

PowerShell : https://codeload.github.com/farag2/Windows-10-Setup-Script/zip/master

- Windows build: 1909
- I ran 1909 script

[Windows-10-Setup-Script-master.zip](https://github.com/farag2/Windows-10-Setup-Script/files/5047278/Windows-10-Setup-Script-master.zip)

**Comment by farag2** [comment]
Please fill out the issue as menioned [here](https://github.com/farag2/Windows-10-Setup-Script/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by farag2** [comment]
#50. May be you should uninstall Mail app and install again.
