### ISSUE TITLE
WSL Distro gone after running the script

### ISSUE THREAD

**Issue by rockiger** [farag2/Windows-10-Setup-Script#53]
Sorry for posting this. This is a request for help. I did run the Win.10.2004.4.5.6 script following the Youtube video from Chris Titus. Unlike in the video I chose to create a restore point at the start of the script.

After the script was done. I can't find my Ubuntu 18.04 distro anymore. I recovered to the restore point, but wsl still says there are no distros installed. Unfortunately, I created a pretty big repository that I didn't push to Github. (I know this was stupid! I don't know why I don't created this project.) Do you know if I can undo the distro deletion?

**Desktop (please complete the following information):**
- Windows build: 19042.423

**Comment by farag2** [comment]
Very bad. I'll do some tests...

**Comment by rockiger** [comment]
That would be great. Thank you.

**Comment by farag2** [comment]
Actually I do not how to test but here's my thoughts

```powershell
# Change %TEMP% environment variable path back to default
# https://github.com/microsoft/WSL/issues/5437
if (-not (Test-Path -Path $env:LOCALAPPDATA\Temp))
{
	New-Item -Path $env:LOCALAPPDATA\Temp -ItemType Directory -Force
}
if (-not (Test-Path -Path $env:SystemRoot\TEMP))
{
	New-Item -Path $env:SystemRoot\TEMP -ItemType Directory -Force
}

[Environment]::SetEnvironmentVariable("TMP", "$env:LOCALAPPDATA\Temp", "User")
[Environment]::SetEnvironmentVariable("TMP", "$env:LOCALAPPDATA\Temp", "Machine")
[Environment]::SetEnvironmentVariable("TMP", "$env:LOCALAPPDATA\Temp", "Process")
New-ItemProperty -Path HKCU:\Environment -Name TMP -PropertyType ExpandString -Value %USERPROFILE%\AppData\Local\Temp -Force

[Environment]::SetEnvironmentVariable("TEMP", "$env:SystemDrive\Temp", "User")
[Environment]::SetEnvironmentVariable("TEMP", "$env:SystemDrive\Temp", "Machine")
[Environment]::SetEnvironmentVariable("TEMP", "$env:SystemDrive\Temp", "Process")
New-ItemProperty -Path HKCU:\Environment -Name TEMP -PropertyType ExpandString -Value %USERPROFILE%\AppData\Local\Temp -Force

New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" -Name TMP -PropertyType ExpandString -Value %SystemRoot%\TEMP -Force
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" -Name TEMP -PropertyType ExpandString -Value %SystemRoot%\TEMP -Force



# Adding "swap=0" to the .wslconfig
# https://github.com/microsoft/WSL/issues/5437
if (-not (Test-Path -Path "$env:HOMEPATH\.wslconfig"))
{
	$wslconfig = @"
[wsl2]
swap=0
"@
	# Saving .wslconfig in UTF-8 encoding
	Set-Content -Path "$env:HOMEPATH\.wslconfig" -Value (New-Object System.Text.UTF8Encoding).GetBytes($wslconfig) -Encoding Byte -Force
}
else
{
	$String = Get-Content -Path "$env:HOMEPATH\.wslconfig" | Select-String -Pattern "swap=" -SimpleMatch
	if ($String)
	{
		(Get-Content -Path "$env:HOMEPATH\.wslconfig").Replace("swap=1", "swap=0") | Set-Content -Path "$env:HOMEPATH\.wslconfig" -Force
	}
	else
	{
		Add-Content -Path "$env:HOMEPATH\.wslconfig" -Value "`nswap=0" -Force
	}
}



# Restart required
```

Do not know whether it help. But it'll be better to see what's going on remotely. May be within TeamViewer.

**Comment by farag2** [comment]
Just found in Google: https://dev.to/kapilgorve/move-install-wsl-distro-from-c-drive-to-another-drive-19g9
Does ```lxrunoffline list``` show your distro?

**Comment by tomatsaev** [comment]
I have something else with WSL after running the script, it wont resolve any url, looks like a dns problem. Getting `ping: github.com: Temporary failure in name resolution`

**Comment by farag2** [comment]
#43

**Comment by rockiger** [comment]
Unfortunately this didn't work for me the distro is still not there. Bummer, but I will get over it. I will have to recreate my project. Will be probably faster this time :(.

Anyhow, thanks a lot for caring.

**Comment by farag2** [comment]
Think you should find distro in default folder: https://github.com/MicrosoftDocs/WSL/issues/251
