### ISSUE TITLE
desktop ruined

### ISSUE THREAD

**Issue by callumok2004** [farag2/Windows-10-Setup-Script#54]
So my desktop is now showing the users/Public desktop?? How can I revert this to the old desktop for MY account which is location in users/callu/OneDrive/Desktop

**Comment by farag2** [comment]
The script doesn't provide feature to show Public desktop. What functions did you run? Also did you uninstall OneDrive?

**Comment by farag2** [comment]
https://www.reddit.com/r/PowerShell/comments/go2n5v/powershell_script_setup_windows_10/g2cutiu/
// closed. 👍
