### ISSUE TITLE
Не работает ночной режим(night light) после отключения "CDPSvc"

### ISSUE THREAD

**Issue by alsolovyev** [farag2/Windows-10-Setup-Script#6]
После отключения "**CDPSvc**"(строка 18) перестает запускаться стандартный ночной режим(night light)

Edition: **Windows 10 Pro N**
Version: **1903**
OS build: **18362.295**

Чтобы включить:
```
Get-Service -Name "CDPSvc" | Set-Service -StartupType Automatic
Get-Service -Name "CDPSvc" | Start-Service
```

**Comment by farag2** [comment]
Все возможно. Я проверю. Спасибо за отзыв.
