### ISSUE TITLE
Alt+Tab is showing all my tabs from my browser

### ISSUE THREAD

**Issue by 3005renan** [farag2/Windows-10-Setup-Script#61]
Is there a way to revert this?

**Comment by farag2** [comment]
Firstly, submitthe issue using the template. Secondly, you even didn't mention what your browser is.

**Comment by farag2** [comment]
May be this will help: https://www.howtogeek.com/352028/windows-10-is-changing-how-alttab-works-here’s-what-you-need-to-know/
But I'm not an extrasensory.
