### ISSUE TITLE
How do you apply the script for multiple users?

### ISSUE THREAD

**Issue by pandaero** [farag2/Windows-10-Setup-Script#62]
Hi, I can run this on the administrator account with no problems. When I log in as a non-admin local account I run a powershell as administrator it runs but applies it again on the admin account. None of the actions are applied to the user, the taskbar still has the theme, search bar, and hidden task programs.

**Comment by farag2** [comment]
Hello. You cannot apply it for multiple users because registry key are being set sometimes in HKCU and HKLM hives. So only if a key is set in HKLM hive it will be applied for all user users. That's the Windows paradigm. To do what you're trying to archive you should user GPO. That's the solution.

**Comment by pandaero** [comment]
Thanks! Onwards to figure out how to "user GPO" 😛
