### ISSUE TITLE
windows MSC and control panels not working/ V. Slow

### ISSUE THREAD

**Issue by EmmJSee** [farag2/Windows-10-Setup-Script#63]
Before submitting a bug report:

- Make sure you are able to repro it on the latest released version;
- The .ps1 file has UTF-8 with BOM enconding.

**Steps to reproduce**
------------------
Opening any msc control (such as group policy) or settings  control (such as apps & features) results either in an entirely unresponsive or unpopulated control.

e.g. thr group policy msc took about 7 minutes to become responsive, and then hasn't worked since (at least another 15min).

Apps& Features is unpopulated, as you can see.

**Screenshots**

[
![GroupPolicy](https://user-images.githubusercontent.com/31172706/93538983-a0253580-f9a3-11ea-82fa-bce6586bec4e.PNG)
![Apps features](https://user-images.githubusercontent.com/31172706/93538985-a1566280-f9a3-11ea-9ef3-8ff8905574e0.PNG)

](url)

**Desktop (please complete the following information):**
- Windows build: 2004
**Additional context**One event that did happen after running script and restart: DISM automatically started/checked windows image, though no errors were found).

**Comment by farag2** [comment]
Hello. Never faced such issues. For sure it cannot be script's fault. Did your check OS health?

```cmd
DISM /Online /Cleanup-Image /RestoreHealth
```

then

```cmd
sfc /scannow
```
