### ISSUE TITLE
can't detect second monitor / screen

### ISSUE THREAD

**Issue by kyslmao69** [farag2/Windows-10-Setup-Script#64]
Windows doesn't detect my second monitor. The second monitor is using HDMI and I hooked up my laptop (hasn't been debloated) to be sure the screen still works, which it does. My Windows PC just can't detect the screen, I tried replugging the HDMI and power cable in the pc and also in the screen itself. My main monitor using displayport cable works fine tho. 
I'm on windows build 19041.508.

**Comment by farag2** [comment]
Hello. Does the Settings app detect the second monitor? I do not think that it's the script fault 'coz actually it isn't a deblot script; it's for fine-tuning. I used to connect the second monitor to my PC at work. Saw nothing issues. Need more time to figure out...

**Comment by kyslmao69** [comment]
My apologies, appeared to be a driver issue on my end, script didn't cause it.

**Comment by farag2** [comment]
I knew it from the beginning ))
