### ISSUE TITLE
Backport options

### ISSUE THREAD

**Issue by zer0kz** [farag2/Windows-10-Setup-Script#7]
Option to exclude some part of changes does not exists.
For example, right now i am trying to get back new WIn10 Start menu view and Miscrosoft solarite game (don't ask me why :) on several wrokstations in a corporate domain.

**Comment by farag2** [comment]
@zer0kz, Please, give more description for your problem. I did not understand. What should I exclude?

**Comment by Avallagni** [comment]
If i get him right - he means "checkboxes" yes or no - to delete separate parts of some packets. Not only full-or-none option. Using this - u can delete all MS Games exept MS Solitaire. And etc.

**Comment by zer0kz** [comment]
> @zer0kz, Please, give more description for your problem. I did not understand. What should I exclude? MS Solitaire?

Sorry for misunderstanding, @Avallagni is right - an option to select needed functions and exclude some parts during script execution will be helpful.
