### ISSUE TITLE
OneDrive not found and other errors

### ISSUE THREAD

**Issue by SerikDM** [farag2/Windows-10-Setup-Script#8]
I did run this script three times, fails with such errors.

Errors
Line Error
---- -----
1607 Cannot find path 'C:\WINDOWS\Temp' because it does not exist.
1603 Cannot find path 'C:\Users\Username\AppData\Local\Temp' because it does not exist.
1600 Cannot find path 'C:\PerfLogs' because it does not exist.
1062 No MSFT_Printer objects found with property 'Name' equal to 'Microsoft Print to PDF'.  Verify the value of the
     property and retry.
1062 No MSFT_Printer objects found with property 'Name' equal to 'Microsoft XPS Document Writer'.  Verify the value of
     the property and retry.
1062 No MSFT_Printer objects found with property 'Name' equal to 'Fax'.  Verify the value of the property and retry.
1036 Cannot find path 'D:\Desktop\Microsoft Edge.lnk' because it does not exist.
 990 Property NullFile does not exist at path HKEY_CLASSES_ROOT\.bmp\ShellNew.
 989 Property ItemName does not exist at path HKEY_CLASSES_ROOT\.bmp\ShellNew.
 986 Property ItemName does not exist at path HKEY_CLASSES_ROOT\.rtf\ShellNew.
 985 Property Data does not exist at path HKEY_CLASSES_ROOT\.rtf\ShellNew.
 982 Cannot find path 'HKEY_CLASSES_ROOT\.zip\CompressedFolder\ShellNew' because it does not exist.
 913 Property Extended does not exist at path HKEY_CLASSES_ROOT\exefile\shell\runasuser.
 890 Cannot bind parameter 'Name'. Cannot convert value to type System.String.
 799 Cannot find path 'J:\Программы\Прочее' because it does not exist.
 799 Cannot find path 'D:\Программы\Прочее' because it does not exist.
 594 Cannot find path 'C:\Users\Serik\OneDrive' because it does not exist.
 593 Property OneDrive does not exist at path HKEY_CURRENT_USER\Environment.
 581 Cannot find a process with the name "OneDrive". Verify the process name and call the cmdlet again.

**Comment by farag2** [comment]
Hello. As you wrote, you had run scrip three times, and of course these folders can not be deleted three times.
So these errors aren't errors. Just script informs, that folders and registry keys were removed before.

**Comment by SerikDM** [comment]
@farag2 But I've got half of theese errors even after first run.
Or is it just an info about how process done? I thought this is crit. error and process stopped.

**Comment by farag2** [comment]
@SerikDM, no if you had run script and saw these errors, that means only that these folders and registry keys do not exist. I do not know why (that is not critical), but I advice to recall, why did you delete them. 
The process doesn't stop at these kind of errors. It indicates them only at the end. Anyway if there are no there keys and folders, they can not be deleted. :)
