### ISSUE TITLE
Error due to unicode ?

### ISSUE THREAD

**Issue by MyTheValentinus** [farag2/Windows-10-Setup-Script#9]
Hello
I'm unable to run your script, i think is due to characters problem ?
See my attatchment
![error](https://user-images.githubusercontent.com/6104498/64122770-d1d05c00-cda2-11e9-9753-d1cd17a81870.PNG)

Windows build version:  18362.295
Thanks

**Comment by farag2** [comment]
Hello!
Did you save .ps1 file in "UTF-8 with BOM" encoding as I mentioned in the article?

**Comment by MyTheValentinus** [comment]
Hmm, yeah okay i miss to change UTF-8-BOM with latest downloaded script.
Thanks you
